apiVersion: v1
kind: Service
metadata:
  name: {{ include "rush.componentName" (dict "root" . "component" "frontend") }}
  labels:
    {{- include "rush.componentLabels" (dict "root" . "component" "frontend") | nindent 4 }}
spec:
  type: {{ .Values.frontend.service.type }}
  ports:
    - name: http
      port: {{ .Values.frontend.service.port }}
      targetPort: http
  selector:
    {{- include "rush.selectorLabels" (dict "root" . "component" "frontend") | nindent 4 }}
