{{- if and .Values.queryApi.ingress.enabled .Values.queryApi.ingress.frontend.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "rush.componentName" (dict "root" . "component" "frontend") }}
  labels:
    {{- include "rush.componentLabels" (dict "root" . "component" "frontend") | nindent 4 }}
  {{- with .Values.queryApi.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- with .Values.queryApi.ingress.className }}
  ingressClassName: {{ . | quote }}
  {{- end }}
  {{- if .Values.queryApi.ingress.frontend.tls.enabled }}
  tls:
    - hosts:
        - {{ .Values.queryApi.ingress.frontend.host | quote }}
      {{- with .Values.queryApi.ingress.frontend.tls.secretName }}
      secretName: {{ . | quote }}
      {{- end }}
  {{- end }}
  rules:
    - host: {{ .Values.queryApi.ingress.frontend.host | quote }}
      http:
        paths:
          - path: {{ .Values.queryApi.ingress.frontend.path | quote }}
            pathType: {{ .Values.queryApi.ingress.frontend.pathType }}
            backend:
              service:
                name: {{ include "rush.componentName" (dict "root" . "component" "frontend") }}
                port:
                  name: http
{{- end }}
{{- if and .Values.queryApi.ingress.enabled .Values.queryApi.ingress.api.enabled }}
---
{{- $annotations := mergeOverwrite (deepCopy (.Values.queryApi.ingress.annotations | default dict)) (deepCopy (.Values.queryApi.ingress.api.annotations | default dict)) }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "rush.componentName" (dict "root" . "component" "query-api") }}
  labels:
    {{- include "rush.componentLabels" (dict "root" . "component" "query-api") | nindent 4 }}
  {{- with $annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- with .Values.queryApi.ingress.className }}
  ingressClassName: {{ . | quote }}
  {{- end }}
  {{- if .Values.queryApi.ingress.api.tls.enabled }}
  tls:
    - hosts:
        - {{ .Values.queryApi.ingress.api.host | quote }}
      {{- with .Values.queryApi.ingress.api.tls.secretName }}
      secretName: {{ . | quote }}
      {{- end }}
  {{- end }}
  rules:
    - host: {{ .Values.queryApi.ingress.api.host | quote }}
      http:
        paths:
          - path: {{ .Values.queryApi.ingress.api.path | quote }}
            pathType: {{ .Values.queryApi.ingress.api.pathType }}
            backend:
              service:
                name: {{ include "rush.queryApiServiceName" . }}
                port:
                  name: http
{{- end }}
