{{- if ne .Values.clickhouse.mode "external" -}}
{{- $secretName := "rushobs-clickhouse-credentials" -}}
{{- $existingSecret := lookup "v1" "Secret" .Release.Namespace $secretName -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $secretName }}
  labels:
    app.kubernetes.io/component: clickhouse
    {{- include "rush.labels" . | nindent 4 }}
  annotations:
    "helm.sh/resource-policy": keep
type: Opaque
data:
  user: {{ "default" | b64enc }}
  {{- if $existingSecret }}
  password: {{ index $existingSecret.data "password" }}
  {{- else }}
  password: {{ randAlphaNum 24 | b64enc }}
{{- end }}
---
{{ $readSecretName := "rushobs-clickhouse-read-credentials" }}
{{ $existingReadSecret := lookup "v1" "Secret" .Release.Namespace $readSecretName }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $readSecretName }}
  labels:
    app.kubernetes.io/component: clickhouse
    {{- include "rush.labels" . | nindent 4 }}
  annotations:
    "helm.sh/resource-policy": keep
type: Opaque
data:
  user: {{ "rushquery" | b64enc }}
  {{- if $existingReadSecret }}
  password: {{ index $existingReadSecret.data "password" }}
  {{- else }}
  password: {{ randAlphaNum 32 | b64enc }}
  {{- end }}
{{- end }}
