{{- if and .Values.enterprise.postgresCollector.enabled .Values.enterprise.postgresCollector.serviceAccount.create }}
{{ include "rush.serviceAccount" (dict "root" . "workload" .Values.enterprise.postgresCollector "component" "postgres-collector") }}
---
{{- end }}
{{- if and .Values.enterprise.mysqlCollector.enabled .Values.enterprise.mysqlCollector.serviceAccount.create }}
{{ include "rush.serviceAccount" (dict "root" . "workload" .Values.enterprise.mysqlCollector "component" "mysql-collector") }}
---
{{- end }}
{{- if and (include "rush.stackOtelEnabled" .) .Values.collectors.otel.serviceAccount.create }}
{{ include "rush.serviceAccount" (dict "root" . "workload" .Values.collectors.otel "component" "otel-collector") }}
{{- end }}
