{{- if and .Values.rush.queryApi.config.integrations.sreAgent.enabled .Values.rush.queryApi.config.integrations.sreAgent.podDisruptionBudget.enabled }}
{{ include "rush.podDisruptionBudget" (dict "root" . "component" "sre-agent" "pdb" .Values.rush.queryApi.config.integrations.sreAgent.podDisruptionBudget) }}
---
{{- end }}
{{- if and .Values.mysqlCollector.enabled .Values.mysqlCollector.podDisruptionBudget.enabled }}
{{ include "rush.podDisruptionBudget" (dict "root" . "component" "mysql-collector" "pdb" .Values.mysqlCollector.podDisruptionBudget) }}
---
{{- end }}
{{- if and .Values.postgresCollector.enabled .Values.postgresCollector.podDisruptionBudget.enabled }}
{{ include "rush.podDisruptionBudget" (dict "root" . "component" "postgres-collector" "pdb" .Values.postgresCollector.podDisruptionBudget) }}
---
{{- end }}
{{- if and (include "rush.stackOtelEnabled" .) .Values.collectors.otel.podDisruptionBudget.enabled }}
{{ include "rush.podDisruptionBudget" (dict "root" . "component" "otel-collector" "pdb" .Values.collectors.otel.podDisruptionBudget) }}
---
{{- end }}
{{- if and (include "rush.stackVectorEnabled" .) .Values.collectors.vector.podDisruptionBudget.enabled }}
{{ include "rush.podDisruptionBudget" (dict "root" . "component" "vector" "pdb" .Values.collectors.vector.podDisruptionBudget) }}
{{- end }}
