{{- if and .Values.postgresCollector.enabled .Values.postgresCollector.serviceAccount.create }}
{{ include "rush.serviceAccount" (dict "root" . "workload" .Values.postgresCollector "component" "postgres-collector") }}
---
{{- end }}
{{- if and (include "rush.stackOtelEnabled" .) .Values.collectors.otel.serviceAccount.create }}
{{ include "rush.serviceAccount" (dict "root" . "workload" .Values.collectors.otel "component" "otel-collector") }}
{{- end }}
