{{- if .Values.rush.queryApi.config.integrations.sreAgent.enabled }}
{{ include "rush.serviceAccount" (dict "root" . "workload" .Values.rush.queryApi.config.integrations.sreAgent "component" "sre-agent") }}
{{- end }}
