{{- if .Values.rush.queryApi.config.integrations.sreAgent.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "rush.sreAgentServiceName" . }}
  labels:
    {{- include "rush.componentLabels" (dict "root" . "component" "sre-agent") | nindent 4 }}
spec:
  type: {{ .Values.rush.queryApi.config.integrations.sreAgent.service.type }}
  ports:
    - name: http
      port: {{ .Values.rush.queryApi.config.integrations.sreAgent.service.port }}
      targetPort: http
  selector:
    {{- include "rush.selectorLabels" (dict "root" . "component" "sre-agent") | nindent 4 }}
{{- end }}
